# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

# This is mostly intended to ease with GitHub Action workflows

[tools]
pesde = "pesde-pkg/pesde@0.7.0+registry.0.2.3"
StyLua = "JohnnyMorganz/StyLua@2.1.0"
